---
title: 'Practical Machine Learning'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: 'Anderson H Uyekita'
  course: 'Practical Machine Learning'
  course_url: 'https://www.coursera.org/learn/practical-machine-learning'
  specialization: 'Data Science: Foundations using R Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-foundations-r'
  instructor: 'Jeff Leek'
  course_start: !r lubridate::ymd('2022/07/10', tz = 'America/Sao_Paulo')
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  certificate_url: './'
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(params$certificate_url != "./") {sprintf(fmt = "* &#x1F393; [Certificate](%s)", params$certificate_url)}`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F680; Course Project 1 Repository](https://github.com/AndersonUyekita/practical-machine-learning_course-project)
* [&#x1F4DD; Quiz 1](./Week 1/quiz-1_practical-machine-learning.md)
* [&#x1F4DD; Quiz 2](./Week 2/quiz-2_practical-machine-learning.md)
* [&#x1F4DD; Quiz 3](./Week 3/quiz-3_practical-machine-learning.md)
* [&#x1F4DD; Quiz 4](./Week 4/quiz-4_practical-machine-learning.md)

#### Class Notes

* [&#x1F4C6; Week 1](./Week 1)
* [&#x1F4C6; Week 2](./Week 2)
* [&#x1F4C6; Week 3](./Week 3)
* [&#x1F4C6; Week 4](./Week 4)

#### Course Description

One of the most common tasks performed by data scientists and data analysts are prediction and machine learning. This course will cover the basic components of building and applying prediction functions with an emphasis on practical applications. The course will provide basic grounding in concepts such as training and tests sets, overfitting, and error rates. The course will also introduce a range of model based and algorithmic machine learning methods including regression, classification trees, Naive Bayes, and random forests. The course will cover the complete process of building prediction functions including data collection, feature creation, algorithms, and evaluation.

#### Course Syllabus

* Prediction study design
* In sample and out of sample errors
* Overfitting
* Receiver Operating Characteristic (ROC) curves
* The caret package in R
* Preprocessing and feature creation
* Prediction with regression
* Prediction with decision trees
* Prediction with random forests
* Boosting
* Prediction blending

#### Course Projects




